databases:
  - name: mydb
    plan: free

services:
  - type: web
    name: django-app
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn SchoolManagement.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mydb
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: SchoolManagement.settings
      - key: PYTHON_VERSION
        value: 3.11
